export interface ModInfos {
    name: String,
    summary: String,
    description: String,
    picture_url: String,
    mod_downloads: number,
    mod_unique_downloads: number,
    uid: number,
    mod_id: number,
    game_id: number,
    allow_rating: boolean,
    domain_name: String,
    category_id: number,
    version: String,
    endorsement_count: number,
    created_timestamp: number,
    created_time: String,
    updated_timestamp: number,
    updated_time: String,
    author: String,
    uploaded_by: String,
    uploaded_users_profile_url: String,
    contains_adult_content: boolean,
    status: String,
    available: boolean,
    invisible: boolean
}